
name: Release

on:
  release:
    types: 
      - released

#jobs:
#  publish:
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 14.17
#      - run: npm install
#      - run: npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_CONTEXT"
      - name: Echo release tag
        run: echo ${{ github.event.release.tag_name }} ${{ secrets.GITHUB_TOKEN }}